In [6]:
import os
import zipfile
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models

In [7]:
with zipfile.ZipFile("leapGestRecog.zip", 'r') as zip_ref:
    zip_ref.extractall("hand_gestures_dataset")

In [8]:
ds= 'hand_gestures_dataset'

In [9]:
dg = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

In [10]:
image_size = (128, 128)
batch_size = 32

image_size = (128, 128)
batch_size = 32

train_generator = dg.flow_from_directory(
    os.path.join(ds),
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

test_generator = dg.flow_from_directory(
    os.path.join(ds),
    target_size=image_size,
    batch_size=batch_size,
    class_mode='categorical'
)

Found 40000 images belonging to 1 classes.
Found 40000 images belonging to 1 classes.


In [11]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))

In [12]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [13]:
model.fit(train_generator, epochs=5, validation_data=test_generator, steps_per_epoch=1000)

Epoch 1/5
1000/1000 [==============================] - 1497s 1s/step - loss: 737.6347 - accuracy: 0.0018 - val_loss: 734.4830 - val_accuracy: 6.7500e-04
Epoch 2/5
1000/1000 [==============================] - 1150s 1s/step - loss: 734.4788 - accuracy: 0.0082 - val_loss: 734.4830 - val_accuracy: 0.0084
Epoch 3/5
1000/1000 [==============================] - 1102s 1s/step - loss: 734.4788 - accuracy: 0.0078 - val_loss: 734.4830 - val_accuracy: 0.0073
Epoch 4/5
1000/1000 [==============================] - 1146s 1s/step - loss: 734.4788 - accuracy: 0.0059 - val_loss: 734.4830 - val_accuracy: 0.0000e+00
Epoch 5/5
1000/1000 [==============================] - 943s 943ms/step - loss: 734.4788 - accuracy: 0.0048 - val_loss: 734.4830 - val_accuracy: 1.0000e-04


In [14]:
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np

# Generate predictions
Y_pred = model.predict(test_generator)
y_pred = np.argmax(Y_pred, axis=1)  # Assuming the model output is one-hot encoded

# Get true labels
y_true = test_generator.classes

# Print confusion matrix and classification report
conf_matrix = confusion_matrix(y_true, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

class_report = classification_report(y_true, y_pred, labels=np.unique(y_true))
print("\nClassification Report:")
print(class_report)

1250/1250 [==============================] - 461s 368ms/step
Confusion Matrix:
[[  6 114 495 ...  12   7   4]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.00      0.00     40000

   micro avg       1.00      0.00      0.00     40000
   macro avg       1.00      0.00      0.00     40000
weighted avg       1.00      0.00      0.00     40000

